"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.GET_COMMITS = exports.SELECTED_REPOSITORY = exports.GET_REPOSITORIES = void 0;
var GET_REPOSITORIES = "GET_REPOSITORIES";
exports.GET_REPOSITORIES = GET_REPOSITORIES;
var SELECTED_REPOSITORY = "SELECTED_REPOSITORY";
exports.SELECTED_REPOSITORY = SELECTED_REPOSITORY;
var GET_COMMITS = "GET_COMMITS";
exports.GET_COMMITS = GET_COMMITS;